export {
  ArtefactPreview,
  CourseCapabilityConstellation,
  CourseMetadataPanel,
  CourseOutcomeStatement,
  CourseOutputsList,
  CourseProgressionMap,
  CourseStatusBlock,
  FeaturedWorkshopPanel,
  FlagshipCourseFeature,
  FoundationCourseEntry,
  ProgrammeWaitlistCTA,
  SpecialistCourseCard,
  TeamTrainingPanel,
  WorkshopRow,
  WorkshopScheduleBoard,
  type FlagshipCourseFeatureProps,
  type FoundationCourseEntryProps,
  type ProgrammeWaitlistCTAProps,
  type SpecialistCourseCardProps,
  type WorkshopRowProps,
} from "./programme-components";
export { ArtefactEvidenceBoard } from "./artefact-evidence-board";
export {
  artefactFixtures,
  flagshipProgramme,
  foundationProgramme,
  programmeFixtures,
  specialistProgrammes,
  workshopFixtures,
  type ArtefactFixture,
  type ProgrammeCapability,
  type ProgrammeCategory,
  type ProgrammeFixture,
  type WorkshopFixture,
} from "./programme-data";
