export {
  ArtefactPreview,
  CourseCapabilityConstellation,
  CourseMetadataPanel,
  CourseOutcomeStatement,
  CourseOutputsList,
  CourseProgressionMap,
  CourseStatusBlock,
  FeaturedWorkshopPanel,
  FlagshipCourseFeature,
  FoundationCourseEntry,
  ProgrammeWaitlistCTA,
  SpecialistCourseCard,
  TeamTrainingPanel,
  WorkshopRow,
  WorkshopScheduleBoard,
  type FlagshipCourseFeatureProps,
  type FoundationCourseEntryProps,
  type ProgrammeWaitlistCTAProps,
  type SpecialistCourseCardProps,
  type WorkshopRowProps,
} from "./programme-components";
export { ArtefactEvidenceBoard } from "./artefact-evidence-board";
export {
  ALL_COURSES_INTEREST,
  artefactFixtures,
  flagshipProgramme,
  foundationProgramme,
  isWaitlistInterestSlug,
  normalizeWaitlistInterest,
  programmeFixtures,
  specialistProgrammes,
  waitlistInterestSlugs,
  workshopFixtures,
  type ArtefactFixture,
  type ProgrammeCapability,
  type ProgrammeCategory,
  type ProgrammeFixture,
  type ProgrammeSlug,
  type WaitlistInterestSlug,
  type WorkshopFixture,
  type WorkshopSlug,
} from "./programme-data";
