export {
  ArticleProse,
  ArticleTableOfContents,
  AuthorByline,
  CodePromptBlock,
  ComingSoonResource,
  DownloadableArtefact,
  EvidenceCallout,
  FeaturedResource,
  FounderCareerTimeline,
  MediaFigure,
  NewsletterIssuePreview,
  NewsletterThemesMap,
  PrincipleBlock,
  PullQuote,
  RelatedProgrammeCTA,
  ResourceCategoryLabel,
  ResourceListItem,
  ResourceMetadata,
  TeachingPrinciplesSection,
} from "./editorial-components";
export {
  articleSections,
  founderTimeline,
  newsletterThemes,
  publishedArticleSpecimen,
  resourceFixtures,
  teachingPrinciples,
  type ArticleSectionFixture,
  type ResourceCategory,
  type ResourceFixture,
  type ResourceStatus,
  type TimelineFixture,
} from "./editorial-data";
